CREATE TABLE AUDIT (
AUDIT_KEY INT NOT NULL AUTO_INCREMENT,
AUDIT_DATE datetime DEFAULT NULL,
SERVICE_ID VARCHAR(100) DEFAULT NULL,
IP_ADDRESS VARCHAR(500) NOT NULL,
PRIMARY KEY (AUDIT_KEY)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;