CREATE TABLE USER (
USER_KEY INT NOT NULL AUTO_INCREMENT,
USER_ID VARCHAR(50) NOT NULL,
USER_PSWD VARCHAR(500) NOT NULL,
USER_NAME VARCHAR(100) NOT NULL,
PRIMARY KEY (USER_KEY),
UNIQUE KEY UK_username (USER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;